<<<<<<< HEAD
# Generated by Django 2.2.3 on 2019-07-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userID', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('nick', models.CharField(max_length=10)),
            ],
        ),
    ]
=======
# Generated by Django 2.2.3 on 2019-07-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userID', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('nick', models.CharField(max_length=10)),
            ],
        ),
    ]
>>>>>>> 2480c54b8f7df51e28a370924a66f630a3ddc302
